name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Validate unit tests
        run: go test ./... -cover

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      # another option instead of go install is use the github action for staticcheck
      # - uses: dominikh/staticcheck-action@v1
      # with:
      # version: "latest"

      - name: Check proper style
        run: test -z $(go fmt ./...)

      - name: Check lint
        run: test -z $(staticcheck ./...)
